export const GET_SOCIAL_LINKS = 'GET_SOCIAL_LINKS';
export const PATCH_SOCIAL_LINKS = 'PATCH_SOCIAL_LINKS';
export const GET_DOCUMENTATION = 'GET_DOCUMENTATION';
export const PATCH_DOCUMENTATION = 'PATCH_DOCUMENTATION';
export const GET_BASIC_INFO = 'GET_BASIC_INFO';
export const PATCH_BASIC_INFO = 'PATCH_BASIC_INFO';

export const RETRIVE_EMPLOYEE_IDENTITY_PAN_DATA = "RETRIVE_EMPLOYEE_IDENTITY_PAN_DATA"
export const RETRIVE_EMPLOYEE_IDENTITY_ADHAR_DATA = "RETRIVE_EMPLOYEE_IDENTITY_ADHAR_DATA"
export const RETRIVE_EMPLOYEE_IDENTITY_DL_DATA = "RETRIVE_EMPLOYEE_IDENTITY_DL_DATA"
export const RETRIVE_EMPLOYEE_IDENTITY_PASSPORT_DATA = "RETRIVE_EMPLOYEE_IDENTITY_PASSPORT_DATA"

 

export const POST_EMPLOYEE_IDENTITY_PAN_DATA = "POST_EMPLOYEE_IDENTITY_PAN_DATA"
export const POST_EMPLOYEE_IDENTITY_ADHAR_DATA = "POST_EMPLOYEE_IDENTITY_ADHAR_DATA"
export const POST_EMPLOYEE_IDENTITY_DL_DATA = "POST_EMPLOYEE_IDENTITY_DL_DATA"
export const POST_EMPLOYEE_IDENTITY_PASSPORT_DATA = "POST_EMPLOYEE_IDENTITY_PASSPORT_DATA"